server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://ym:123456@120.79.192.122:27017/admin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/carabao?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      max-active: 20
      initial-size: 10
      min-idle: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      filters: stat,wall,slf4j
      max-open-prepared-statements: 20
  jackson:
    # 设置不给前端返回null字段
    default-property-inclusion: non_null


# 日志
logging:
  file: logs/mongo.log
  level:
    com.carabao.statistics.mapper: debug
    root: info
  pattern:
    file: '[mongo] %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
